export * from './school-course.controller';
export * from './course-student.controller';
export * from './course-subject.controller';
export * from './professor-subject.controller';
export * from './school.controller';
export * from './course.controller';
export * from './student.controller';
export * from './subject.controller';
export * from './professor.controller';
